-- Multi-chain: same on-chain bot_id can exist on multiple chains (e.g. bot 1
-- on Base mainnet AND bot 1 on Base Sepolia). We split the column that came
-- from the chain (`on_chain_bot_id`) from the DB-side autoincrementing PK
-- (`bot_id`). The unique constraint enforces no in-chain duplicates.
--
-- For existing rows (1 sepolia test bot), on_chain_bot_id is just whatever
-- bot_id already was.

alter table bot_registry.bots
  add column if not exists on_chain_bot_id bigint;

update bot_registry.bots set on_chain_bot_id = bot_id where on_chain_bot_id is null;

alter table bot_registry.bots
  alter column on_chain_bot_id set not null;

alter table bot_registry.bots
  add constraint bots_chain_onchainid_unique unique (chain, on_chain_bot_id);

-- Switch bot_id from "= on-chain id" to "= auto-increment PK".
-- Reset the sequence so new inserts don't collide with existing rows.
alter table bot_registry.bots
  alter column bot_id add generated by default as identity;

select setval(
  pg_get_serial_sequence('bot_registry.bots', 'bot_id'),
  coalesce((select max(bot_id) from bot_registry.bots), 0) + 1,
  false
);

create index if not exists bots_chain_onchainid_idx
  on bot_registry.bots (chain, on_chain_bot_id);
